Answers api
d4got10/platform-for-online-internships pull request #10
Opened 2023-05-16 03:31 UTC by d4got10

2023-05-16 03:56 UTC, d4got10 commented
@Quatters у меня твоя правка была в миграциях. Плохо будет если я твою просто удалю?

2023-05-16 04:13 UTC, Quatters commented
> @Quatters у меня твоя правка была в миграциях. Плохо будет если я твою просто удалю?

да можно удалить без проблем

2023-05-16 10:32 UTC, Quatters requested changes

2023-05-16 10:32 UTC, Quatters commented on backend/migrations/versions/9040106a2ac7_create_task.py
> +    sa.Column('description', sa.String(), nullable=True),
@d4got10 эти поля наверное не должны быть nullable. `topic_id` тоже

2023-05-16 10:32 UTC, Quatters commented on backend/migrations/versions/9040106a2ac7_create_task.py
> +    op.create_index(op.f('ix_app_task_name'), 'app_task', ['name'], unique=True)
@d4got10 `name` сам по себе вряд ли уникальным должен быть, разве что вместе с `topic_id`. Но и то в принципе незачем.

2023-05-16 10:32 UTC, Quatters commented on backend/migrations/versions/ab35b63119c0_create_answer.py
> +    sa.Column('task_id', sa.Integer(), nullable=True),
@d4got10 здесь тоже `nullable` смущает

2023-05-16 10:32 UTC, Quatters commented on backend/api/routes/topics.py
> +    return queries.get_topics(db, course.id)
@d4got10 добавишь пагинацию с поиском по аналогии с курсами? Ну и для других списковых эндпоинтов тоже. Там все просто, только стоит обратить внимание, что есть `fastapi_pagination.paginate`, который работает на уровне питона, а есть `fastapi_pagination.ext.sqlalchemy.paginate`, который на уровне базы. Второй предпочтительнее, но если запрос выходит сложнее, можешь глянуть как я в `user_courses` сделал.

2023-05-16 10:32 UTC, Quatters commented on backend/models/answers.py
> +    task = Relationship(Task, primaryjoin=task_id == Task.id)
@d4got10 кстати, а как `sqlalchemy` по дефолту с удалением родительских записей работает? Тут по-хорошему каскад нужен.

2023-05-16 10:34 UTC, Quatters commented on backend/api/routes/topics.py
> +    return queries.get_topics(db, course.id)
>если запрос выходит сложнее, можешь глянуть как я в user_courses сделал

или если будут идеи лучше, сделать лучше, не уверен, что там наиболее оптимально

2023-05-16 10:38 UTC, Quatters commented
@d4got10 я так мельком глянул, насколько понял, тут пока только круд для админа. Надо тогда тут все закончить, чтоб я этот круд делал на фронте, а то там сейчас нечем заняться)

2023-05-16 14:13 UTC, d4got10 commented
> @d4got10 я так мельком глянул, насколько понял, тут пока только круд для админа. Надо тогда тут все закончить, чтоб я этот круд делал на фронте, а то там сейчас нечем заняться)

Мне тогда зарезолвить треды, тесты пофиксить и с драфта убирать?

2023-05-16 14:15 UTC, d4got10 commented
Еще пока удаление связных сущностей (которые ссылаются на предыдущие) не восстанавливает целостность (не проставляет у тех, кто на них ссылается новые), это тоже тогда сделаю к предыдущим правкам

2023-05-16 14:50 UTC, Quatters commented
> > @d4got10 я так мельком глянул, насколько понял, тут пока только круд для админа. Надо тогда тут все закончить, чтоб я этот круд делал на фронте, а то там сейчас нечем заняться)
> 
> Мне тогда зарезолвить треды, тесты пофиксить и с драфта убирать?


Да, лучше просто понемногу, но чаще, чтоб мы могли параллельно все это пилить

2023-05-16 14:52 UTC, Quatters commented
> Еще пока удаление связных сущностей (которые ссылаются на предыдущие) не восстанавливает целостность (не проставляет у тех, кто на них ссылается новые), это тоже тогда сделаю к предыдущим правкам

если апи, схема не поменяются (или хотя бы не сильно), то ок, можно в следующем тогда сделать

2023-05-16 15:00 UTC, Quatters commented
WIP #6 #2

2023-05-16 15:39 UTC, Quatters requested changes

2023-05-16 15:39 UTC, Quatters commented on backend/api/queries/topics.py
> +    return db.query(Topic).filter(and_(Topic.course_id == course_id, Topic.id == topic_id)).one_or_none()
@d4got10 вроде можно вместо `and_` использовать `(expr1) & (expr2)`. Некритично, но так по-моему привычнее

2023-05-16 15:39 UTC, Quatters commented on backend/api/routes/answers.py
> +@router.get('/', response_model=Union[list[schemas.AnswerAdmin], list[schemas.Answer]])
@d4got10 а вот вместо `typing.Union` начиная с `python 3.10` можно использовать `type1 | type2`

2023-05-16 15:39 UTC, Quatters commented on backend/api/routes/answers.py
> +        raise unauthorized()
@d4got10 у нас тут много таких проверок, может лучше сделать dependency? Они для таких случаев как раз неплохо смотрятся

2023-05-16 15:39 UTC, Quatters commented on backend/models/tasks.py
> +    prev_task_id = Column(Integer, ForeignKey('app_task.id'), index=True, unique=True)
@d4got10 а `Relationship` для него будет?) Вроде можно первым аргументом строку скормить с именем класса

2023-05-16 15:39 UTC, Quatters commented on backend/models/topics.py
> +    #prev_topic = Relationship('app_topic', remote_side='app_topic.id', backref='next_topic')
@d4got10 не получилось?)

2023-05-16 15:54 UTC, Quatters requested changes

2023-05-16 15:54 UTC, Quatters commented on backend/api/queries/topics.py
> +    return db.query(Topic).filter(Topic.course_id == course_id).all()
@d4got10 надо бы сортировать от первого к последнему

2023-05-16 15:54 UTC, Quatters commented on backend/api/schemas/topics.py
> +    prev_topic_id: int | None
@d4got10 надо еще слать `next_topic_id`

2023-05-16 15:54 UTC, Quatters commented on backend/api/schemas/tasks.py
> +    prev_task_id: int | None
@d4got10 тут тоже надо бы `next_task_id` слать

2023-05-17 05:51 UTC, d4got10 commented on backend/api/routes/topics.py
> +    return queries.get_topics(db, course.id)
На ответы же не нужно?

2023-05-17 05:55 UTC, Quatters commented on backend/api/routes/topics.py
> +    return queries.get_topics(db, course.id)
@d4got10 наверное поиск по ним не нужен, а пагинация нужна

2023-05-22 14:05 UTC, merged