Feature(backend): Create competencies api
d4got10/platform-for-online-internships pull request #24
Opened 2023-05-29 06:56 UTC by d4got10

2023-05-29 14:01 UTC, Quatters commented on backend/migrations/versions/ba973b42da5f_create_coursecompetence.py
> +"""Create CourseCompetence
@d4got10 кстати, не знаю, почему у тебя  делаются непустые миграции, если ты не импортишь созданные модели в `backend.models.__init__`, но все равно надо бы туда заимпортить. Алембик по идее смотрит туда, чтоб резолвить, что мигрировать

2023-05-29 14:51 UTC, Quatters commented on backend/api/schemas/course_competencies.py
> +    competence_id: int
@d4got10 блин, ты тут по-другому схему сделал... Давай для m2m в апи не делать промежуточных эндпоинтов, а слать просто список связанных сущностей для одной и второй моделей. Тогда схема будет как в `backend.api.schemas.posts` или [как здесь](https://github.com/d4got10/platform-for-online-internships/pull/23/files#diff-b1685353bbd575a5bb37e21ea6134b8d9df4bf9e3df18e597ac24aa5accdd770)

Т.е. для m2m придерживаться такого подхода: 

```python
FkEntity2Schema:
id: int
...

OneEntity1Schema:
id: int
...
entities2: list[FkEntity2Schema]

FkEntity1Schema:
id: int
...

OneEntity2Schema:
id: int
...
entities1: list[FkEntity1Schema]

CreateEntity1Schema:  # or patch
...
entities1: list[int]  # id list
```

А если связь many-to-one, то делать по аналоги с [этим](https://github.com/d4got10/platform-for-online-internships/pull/23/files#diff-763eda37f70f331ecd54b06e8efdf6c454940ad52f4df75b18cc1cfc91ab52dc).

Просто на фронте у меня уже готовы компоненты под все это дело, если схема будет везде одна, я быстро все подключу. Ну и юзер-воркфлоу везде одинаковый будет.

2023-06-05 05:45 UTC, d4got10 commented
@Quatters

2023-06-05 11:16 UTC, Quatters requested changes

2023-06-05 11:16 UTC, Quatters commented on backend/api/queries/competencies.py
> +    query = with_search(Competence.name, query=db.query(Competence), search=params.search)
@d4got10 тут наверное query=query имелось в виду?

2023-06-05 11:16 UTC, Quatters commented on backend/models/competencies.py
> +if TYPE_CHECKING:
@d4got10 # nocv, эту строчку тестами не покрыть

2023-06-05 11:50 UTC, Quatters commented
поправил тут все

2023-06-05 11:52 UTC, Quatters approved these changes

2023-06-05 11:52 UTC, merged