Update courses API
d4got10/platform-for-online-internships pull request #7
Opened 2023-05-01 17:42 UTC by d4got10

2023-05-01 17:45 UTC, d4got10 commented on backend/api/routes/courses.py
> +    return schemas.DeleteCourse(status="success")
Что сделать лучше возвращать? Или так норм?

2023-05-01 17:48 UTC, d4got10 commented on backend/api/routes/courses.py
> +router = APIRouter(prefix='/course')
В issue был прописан /course, но можем поменять на  /courses

2023-05-01 17:53 UTC, Quatters commented on backend/api/routes/courses.py
> +router = APIRouter(prefix='/course')
как больше нравится, главное чтоб в дальнейшем все было либо в единственном числе, либо во множественном, мне больше во множественном нравится

2023-05-01 18:00 UTC, Quatters commented on backend/api/routes/courses.py
> +    return schemas.DeleteCourse(status="success")
Обычно возвращается 204 на delete с пустым телом ответа. Тут в общем-то success избыточен, статус сам по себе несёт достаточно информации

2023-05-03 07:36 UTC, d4got10 commented
Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз.
Можешь мержить если этого хватит, я продолжу в другой ветке

2023-05-03 10:49 UTC, Quatters commented
> Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз. Можешь мержить если этого хватит, я продолжу в другой ветке

@d4got10 а оставшиеся треды?

2023-05-03 15:34 UTC, d4got10 commented
> > Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз. Можешь мержить если этого хватит, я продолжу в другой ветке
> 
> @d4got10 а оставшиеся треды?

@Quatters  роуты сделал во множественном числе, ответ на удаление поправил, если ты про них

2023-05-03 23:23 UTC, Quatters commented
> > > Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз. Можешь мержить если этого хватит, я продолжу в другой ветке
> > 
> > @d4got10 а оставшиеся треды?
> 
> @Quatters  роуты сделал во множественном числе, ответ на удаление поправил, если ты про них

я же ещё новых написал)

2023-05-04 05:25 UTC, d4got10 commented
> > > > Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз. Можешь мержить если этого хватит, я продолжу в другой ветке
> > > 
> > > 
> > > @d4got10 а оставшиеся треды?
> > 
> > 
> > @Quatters  роуты сделал во множественном числе, ответ на удаление поправил, если ты про них
> 
> я же ещё новых написал)

Ты про issue? Я здесь просто нового ничего не вижу

2023-05-04 05:33 UTC, Quatters requested changes

2023-05-04 05:34 UTC, Quatters commented
> > > > > Тут готово всё кроме Тем материалов и есть багулина с возможностью записи пользователем на один и тот же курс несколько раз. Можешь мержить если этого хватит, я продолжу в другой ветке
> > > > 
> > > > 
> > > > @d4got10 а оставшиеся треды?
> > > 
> > > 
> > > @Quatters  роуты сделал во множественном числе, ответ на удаление поправил, если ты про них
> > 
> > 
> > я же ещё новых написал)
> 
> Ты про issue? Я здесь просто нового ничего не вижу

А, соре, они в pending были)) Я просто их с телефона писал, не понял, как там засабмитить.

2023-05-04 17:33 UTC, d4got10 commented
@Quatters глянь тут ошибку в тесте, ругается на модуль из которого ошибка бд на уникальность ключа, у меня локально тесты проходит. В остальном по тредам сделал правки

2023-05-05 00:06 UTC, Quatters requested changes

2023-05-05 00:06 UTC, Quatters commented on backend/__init__.py
> +from psycopg2.errors import UniqueViolation
@d4got10 ``psycopg2`` напрямую не надо нигде использовать, этой либы в зависимостях нет. Она низкоуровневая и платформо-зависимая, в приложении нужно опираться только на orm. В exception handler'e я думаю достаточно проверять на ``IntegrityError``. Как уберешь импорт, CI должен будет ходить.

2023-05-05 00:06 UTC, Quatters commented on backend/__init__.py
> +        return PlainTextResponse(f"Error: {exc._message()}", status_code=400)
@d4got10 json бы вернуть, мы же rest api делаем)

2023-05-05 00:07 UTC, Quatters commented on backend/migrations/versions/8acc6ed30cb8_create_usercourse.py
> +    # ### end Alembic commands ###
@d4got10 у тебя тут пустые миграции

2023-05-05 00:09 UTC, Quatters commented on backend/migrations/versions/8acc6ed30cb8_create_usercourse.py
> +    # ### end Alembic commands ###
их надо удалить и сделать заново, проверь перед этим, что твоя база полностью смигрирована, вроде ``sqlalchemy`` делает пустые, если это не так

2023-05-05 06:28 UTC, d4got10 commented
@Quatters готово

2023-05-05 06:31 UTC, Quatters approved these changes

2023-05-05 06:31 UTC, merged